name: Render RMarkdown

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R/
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.rmd') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install Pandoc (cache it)
        run: |
          if ! command -v pandoc &> /dev/null
          then
            sudo apt-get install -y pandoc  # Install Pandoc if not installed
          fi

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown"))'  # Install R packages only if not cached

      - name: Render R Markdown
        run: Rscript -e 'rmarkdown::render("code/main.Rmd")'  # Replace with your actual file name

      - name: Commit and push rendered files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-render RMarkdown" || echo "No changes to commit"
          git push
