name: Render RMarkdown

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc  # Install Pandoc manually

      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("rmarkdown"))'
        
      - name: Render R Markdown
        run: Rscript -e 'rmarkdown::render("code/main.Rmd")'  # Change to match your actual file name

      - name: Commit and push rendered files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-render RMarkdown" || echo "No changes to commit"
          git push
